import { ActivityItem, AchievementItem, DaySummary } from '../types';
import { getTodayString, shiftDate } from './dateUtils';

export function getInitialData(): {
  activities: ActivityItem[];
  achievements: AchievementItem[];
  summaries: Record<string, DaySummary>;
} {
  const today = getTodayString();
  const dMinus1 = shiftDate(today, -1);
  const dMinus2 = shiftDate(today, -2);
  const dMinus3 = shiftDate(today, -3);

  const activities: ActivityItem[] = [
    // Today
    {
      id: 'act-today-1',
      date: today,
      time: '07:30 AM',
      endTime: '08:15 AM',
      durationMinutes: 45,
      title: 'Morning 5K Jog & Mobility Work',
      description: 'Pushed the pace in the last kilometer. Felt energized and awake.',
      category: 'health',
      completed: true,
      tags: ['running', 'cardio', 'morning-routine'],
      energyLevel: 'high',
      createdAt: Date.now() - 6 * 3600000,
    },
    {
      id: 'act-today-2',
      date: today,
      time: '09:00 AM',
      endTime: '11:00 AM',
      durationMinutes: 120,
      title: 'Deep Work: Core Feature Implementation',
      description: 'Built out user tracking telemetry and interactive dashboard cards without distractions.',
      category: 'deep-work',
      completed: true,
      isAchievement: true,
      tags: ['coding', 'focus', 'core-product'],
      energyLevel: 'high',
      createdAt: Date.now() - 4 * 3600000,
    },
    {
      id: 'act-today-3',
      date: today,
      time: '11:30 AM',
      endTime: '12:15 PM',
      durationMinutes: 45,
      title: 'Sprint Sync & Cross-Team Review',
      description: 'Aligned on next milestones, resolved blocking PR questions.',
      category: 'tasks',
      completed: true,
      tags: ['team', 'sync', 'management'],
      energyLevel: 'medium',
      createdAt: Date.now() - 3 * 3600000,
    },
    {
      id: 'act-today-4',
      date: today,
      time: '01:30 PM',
      endTime: '02:45 PM',
      durationMinutes: 75,
      title: 'Design System & Micro-animations Polish',
      description: 'Crafted smooth haptic feedback and celebration transitions.',
      category: 'creative',
      completed: true,
      tags: ['ui-ux', 'design', 'polish'],
      energyLevel: 'high',
      createdAt: Date.now() - 2 * 3600000,
    },
    {
      id: 'act-today-5',
      date: today,
      time: '03:15 PM',
      endTime: '03:45 PM',
      durationMinutes: 30,
      title: 'Read 20 Pages: System Design Manual',
      description: 'Highlighted key architecture patterns for resilient distributed event streaming.',
      category: 'learning',
      completed: true,
      tags: ['books', 'growth', 'architecture'],
      energyLevel: 'medium',
      createdAt: Date.now() - 1 * 3600000,
    },
    {
      id: 'act-today-6',
      date: today,
      time: '05:30 PM',
      durationMinutes: 30,
      title: 'Mindful Outdoor Walk & Decompression',
      description: 'Unplugged from screens, listened to ambient sounds in the park.',
      category: 'mindset',
      completed: false,
      tags: ['reset', 'nature'],
      energyLevel: 'medium',
      createdAt: Date.now() - 30 * 60000,
    },

    // Yesterday
    {
      id: 'act-yest-1',
      date: dMinus1,
      time: '08:00 AM',
      durationMinutes: 50,
      title: 'Strength Training Session',
      description: 'New personal best on deadlifts! Kept form solid throughout.',
      category: 'health',
      completed: true,
      isAchievement: true,
      tags: ['gym', 'pr', 'strength'],
      energyLevel: 'high',
      createdAt: Date.now() - 28 * 3600000,
    },
    {
      id: 'act-yest-2',
      date: dMinus1,
      time: '10:00 AM',
      durationMinutes: 150,
      title: 'Database Schema Optimization',
      description: 'Reduced query load times by 42% through compound indexing.',
      category: 'deep-work',
      completed: true,
      isAchievement: true,
      tags: ['database', 'speed', 'dev'],
      energyLevel: 'high',
      createdAt: Date.now() - 25 * 3600000,
    },
    {
      id: 'act-yest-3',
      date: dMinus1,
      time: '02:00 PM',
      durationMinutes: 45,
      title: 'Mentored Junior Colleague on Code Review',
      description: 'Walked through TypeScript generics and automated test patterns.',
      category: 'social',
      completed: true,
      tags: ['mentorship', 'culture'],
      energyLevel: 'medium',
      createdAt: Date.now() - 21 * 3600000,
    },
    {
      id: 'act-yest-4',
      date: dMinus1,
      time: '04:00 PM',
      durationMinutes: 40,
      title: 'Cooked Mediterranean Salmon & Veggies',
      description: 'Home-cooked healthy dinner prep for the next two days.',
      category: 'personal',
      completed: true,
      tags: ['cooking', 'nutrition'],
      energyLevel: 'medium',
      createdAt: Date.now() - 19 * 3600000,
    },

    // 2 days ago
    {
      id: 'act-d2-1',
      date: dMinus2,
      time: '09:00 AM',
      durationMinutes: 180,
      title: 'Finalized Pitch Deck & Demo Prototype',
      description: 'Rehearsed the entire narrative flow with zero stumbles.',
      category: 'deep-work',
      completed: true,
      isAchievement: true,
      tags: ['presentation', 'strategy'],
      energyLevel: 'high',
      createdAt: Date.now() - 50 * 3600000,
    },
    {
      id: 'act-d2-2',
      date: dMinus2,
      time: '03:00 PM',
      durationMinutes: 60,
      title: 'Client Demo Presentation',
      description: 'Client was thrilled with turnaround speed and agreed to contract expansion!',
      category: 'tasks',
      completed: true,
      isAchievement: true,
      tags: ['client-win', 'revenue'],
      energyLevel: 'high',
      createdAt: Date.now() - 44 * 3600000,
    },

    // 3 days ago
    {
      id: 'act-d3-1',
      date: dMinus3,
      time: '08:30 AM',
      durationMinutes: 60,
      title: 'Morning Yoga & Breathwork',
      description: 'Focused on hips and shoulders tension release.',
      category: 'mindset',
      completed: true,
      tags: ['yoga', 'flexibility'],
      energyLevel: 'medium',
      createdAt: Date.now() - 74 * 3600000,
    },
    {
      id: 'act-d3-2',
      date: dMinus3,
      time: '10:30 AM',
      durationMinutes: 120,
      title: 'Refactored Legacy Authentication Module',
      description: 'Replaced fragile session tokens with clean modern tokens.',
      category: 'deep-work',
      completed: true,
      tags: ['security', 'clean-code'],
      energyLevel: 'high',
      createdAt: Date.now() - 72 * 3600000,
    },
  ];

  const achievements: AchievementItem[] = [
    {
      id: 'ach-today-1',
      date: today,
      time: '11:00 AM',
      title: 'Shipped Core Activity & Timeline Engine',
      description: 'Zero-distraction flow session completed with 100% test coverage.',
      impact: 'major',
      category: 'deep-work',
      badgeEmoji: '🚀',
      metric: '2h Deep Focus',
      reflection: 'Staying off social media during the first 3 hours of the day was the game changer.',
      createdAt: Date.now() - 4 * 3600000,
    },
    {
      id: 'ach-today-2',
      date: today,
      time: '08:15 AM',
      title: 'Morning Run 5K Under 24 Minutes',
      description: 'Fastest split this month with consistent pace on elevation.',
      impact: 'meaningful',
      category: 'health',
      badgeEmoji: '⚡',
      metric: '5.0 km • 23:45',
      reflection: 'Sleep quality from yesterday made a visible difference in cardio recovery.',
      createdAt: Date.now() - 6 * 3600000,
    },
    {
      id: 'ach-yest-1',
      date: dMinus1,
      time: '12:30 PM',
      title: '42% Query Latency Cut in Production',
      description: 'Eliminated N+1 query bottlenecks across high-traffic endpoints.',
      impact: 'major',
      category: 'deep-work',
      badgeEmoji: '🔥',
      metric: '42% speedup',
      reflection: 'Deep profiling beats guessing every single time.',
      createdAt: Date.now() - 25 * 3600000,
    },
    {
      id: 'ach-yest-2',
      date: dMinus1,
      time: '08:50 AM',
      title: 'New Personal Best Deadlift: 140kg',
      description: 'Hit the target with crisp form and zero back strain.',
      impact: 'meaningful',
      category: 'health',
      badgeEmoji: '💪',
      metric: '140 kg PR',
      reflection: 'Consistency in warmups paid off.',
      createdAt: Date.now() - 28 * 3600000,
    },
    {
      id: 'ach-d2-1',
      date: dMinus2,
      time: '04:00 PM',
      title: 'Closed Enterprise Demo & Expansion Agreement',
      description: 'Client exec team gave unanimous greenlight for the next quarter.',
      impact: 'major',
      category: 'deep-work',
      badgeEmoji: '🏆',
      metric: '100% Approval',
      reflection: 'Showcasing real problem-solving rather than sales fluff won them over.',
      createdAt: Date.now() - 44 * 3600000,
    },
    {
      id: 'ach-d2-2',
      date: dMinus2,
      time: '07:30 PM',
      title: 'Micro-Win: Clean Desk & Zero Unread Inbox',
      description: 'Organized physical workspace and zeroed out 43 pending emails.',
      impact: 'micro',
      category: 'personal',
      badgeEmoji: '✨',
      metric: 'Inbox 0',
      reflection: 'External order creates internal peace.',
      createdAt: Date.now() - 40 * 3600000,
    },
  ];

  const summaries: Record<string, DaySummary> = {
    [today]: {
      date: today,
      highlight: 'Built key architecture and set a crisp 5K morning pace!',
      mood: 'energized',
      energyRating: 5,
      reflectionWins: 'Crushed deep work session early before any emails came in.',
      reflectionLearnings: 'Batching communication prevents fragmented attention.',
      tomorrowPriority: 'Launch public beta test and gather initial telemetry.',
      waterIntake: 6,
      sleepHours: 7.8,
      habitsChecked: ['h1', 'h2', 'h3', 'h4'],
    },
    [dMinus1]: {
      date: dMinus1,
      highlight: 'Massive database optimization and crushed gym PR.',
      mood: 'ecstatic',
      energyRating: 5,
      reflectionWins: 'Solved the latency issue that was bugging the team for weeks.',
      reflectionLearnings: 'Take time to benchmark before optimizing.',
      tomorrowPriority: 'Lock in core product flow.',
      waterIntake: 8,
      sleepHours: 8.2,
      habitsChecked: ['h1', 'h2', 'h3', 'h4', 'h5'],
    },
    [dMinus2]: {
      date: dMinus2,
      highlight: 'Enterprise deal signoff after high-stakes pitch demo!',
      mood: 'ecstatic',
      energyRating: 5,
      reflectionWins: 'Nailed the presentation live.',
      reflectionLearnings: 'Rehearsing out loud gives effortless confidence.',
      tomorrowPriority: 'Focus on database refactoring.',
      waterIntake: 7,
      sleepHours: 7.5,
      habitsChecked: ['h1', 'h4', 'h5'],
    },
  };

  return { activities, achievements, summaries };
}
